### ISSUE TITLE
Removing custom key/value setting in `ManagedDependentResourceContext` in v5

### ISSUE THREAD

**Issue by csviri** [operator-framework/java-operator-sdk#1922]
Talking about this part:

https://github.com/java-operator-sdk/java-operator-sdk/blob/95f3f0463e82302f50ca1023e433ff517384fa95/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/ManagedDependentResourceContext.java#L15-L41

In core JOSDK at least is nowhere used, and there might have been some cases in the past we though we need this, but don't see any use case now. It is also very confusing, why such key value store should be there. 

So if there are no valid use cases we should delete it, if there is we should add an Integration Test to showcase that.

**Comment by csviri** [comment]
Maybe we should deprecate in next minor version

**Comment by harveyelsom** [comment]
Assuming I have understood this right, we use this custom key/value map feature in our operator and don't really want to see it go.
This concept of a reconcile context makes it easier for us to pass state through each step performed in the reconcile. 
For example I can have an early step in the reconcile that will check the cluster for some state then set that in the context of the reconcile to use in later steps. Sure we could add that check every time we need it but reconcile context map is easy to use and it makes our code way easier to test because we are now just mocking out this map for setup rather than mocking out the resources on the cluster.

**Comment by metacosm** [comment]
I also use this feature in a sample in the Quarkus extension for the purpose of passing around information that is useful for all my dependents instead of re-computing it all the time.
