### ISSUE TITLE
There is no way to perform arbitrary updates on a resource that is marked for deletion

### ISSUE THREAD

**Issue by adriansuarez** [operator-framework/java-operator-sdk#2478]
## Bug Report

The `Reconciler` interface is used to perform reconciliation of resources, but it seems that reconcilers do not receive events about resources that are marked for deletion. The Java Operator SDK allows deletion to be controlled via the `Cleaner` interface, but that only allows deletion to be unblocked by telling the framework to remove the finalizer.

What I would like is to be able to attach a [status condition](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) that explains why the resource cannot be deleted. That seems to be impossible using the framework (unless there is some other mechanism that I don't know about), even though it is possible to do with the Kubernetes API and the Fabric8 client directly.

I guess I can use the Kubernetes client within the `Cleaner.cleanup()` method to perform this update before returning `DeleteControl.noFinalizerRemoval()`, but that does not allow us to benefit from the good features of the framework like automatic retries of updates.

Ideally, what I would like is to be able to configure the controller to allow reconcilers to receive events about all resources, including those that are marked for deletion.

**Comment by csviri** [comment]
Hi @adriansuarez 

>  but it seems that reconcilers do not receive events about resources that are marked for deletion 

This is not true for secondary resources, all events are received. Except for the primary resource, where there is the cleaner as you mentioned. Cleaner is part of the automatic retry functionality. Not sure what you mean by automatic updates, but basically the patterns says that after a resource is marked for deletion, there should be no other operations than removing the finalizer. You can still do updates however (nothing technically prevents it)

> Ideally, what I would like is to be able to configure the controller to allow reconcilers to receive events about all resources, including those that are marked for deletion.

For the primary resources this is very slippery ground, since nothing guarantees that it will receive the delete event if there is no finalizer (thus Cleaner interface),since if the controller is down and not finalizer it will miss the delete event.

> What I would like is to be able to attach a [status condition](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) that explains why the resource cannot be deleted. That seems to be impossible using the framework (unless there is some other mechanism that I don't know about), even though it is possible to do with the Kubernetes API and the Fabric8 client directly.

This is should be perfectly doable in the cleaner interface, with noFinalizerRemoval as you mentioned.

**Comment by adriansuarez** [comment]
Thanks for the quick response, @csviri.

> This is not true for secondary resources, all events are received. Except for the primary resource, where there is the cleaner as you mentioned.

To make sure that I understand your statement, are you saying that if there is an event mapper from secondary to primary that maps kind/resource `B/b` to `A/a`, and `A/a` is marked for deletion, then any event on `B/b` will cause the `Cleaner.cleanup()` method to be invoked on `A/a`?

That is the behavior I would expect, and I think am also observing that behavior in my own testing, so everything looks good.

> This is should be perfectly doable in the cleaner interface, with noFinalizerRemoval as you mentioned.

I have implemented this approach successfully, so feel free to close this issue.
